# Generated by Django 2.1.4 on 2019-07-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starstickergenerator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedimage',
            name='image',
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='sentence',
            field=models.TextField(null=True),
        ),
    ]
