# Generated by Django 2.1.4 on 2019-07-25 01:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('starstickergenerator', '0002_auto_20190724_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_count', models.PositiveIntegerField(null=True)),
                ('exception_count', models.PositiveIntegerField(null=True)),
                ('slug', models.SlugField(default='default')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
