# Generated by Django 2.1.4 on 2019-07-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starstickergenerator', '0003_corpusrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpusrecord',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='corpusrecord',
            name='exception_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
